spring.application.name=jobportal

logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.h2.console.enabled=true

#Default values:

#spring.h2.console.path=/h2-console
#spring.h2.console.enabled=false
#spring.datasource.username=sa
#spring.datasource.password=

#spring.datasource.url=jdbc:h2:mem:testdb

# مش مهم نكتبه اصلا لان spring هيعمل ده لوحده
#spring.datasource.driver-class-name=org.h2.Driver

# if we want to change the name or locations of the sql files
#spring.sql.init.schema-locations=optional:classpath:newPackage/newName.sql
#spring.sql.init.data-locations=optional:classpath:newPackage/newName.sql

spring.datasource.url=jdbc:h2:file:/home/ahmed/Desktop/h2db/jobportal;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=a

spring.sql.init.mode=embedded